schema-version: 1.0

var:
  region: eu-west-3
  type: t2.nano
  size: 20
  amis: #to be filled with system product

const:
  alphabet: efghikjlmnop #used for device mapping. first volume is map to b, second to c ...
  prefix: xv #used for device mapping -> /dev/xvd[x]


provision:
  - url:
      from: https://s3.eu-west-3.amazonaws.com/xbee.repository/providers/linux_amd64/guest.tar.gz
      to: /opt/piper
      after: chmod u+x /opt/piper/guest
  - shell: /opt/piper/guest provision {% alphabet %} {% prefix %}


up: 
  - shell: /opt/piper/guest mount {% alphabet %} {% prefix %}

