schema-version: 1.0

var:
  region: eu-west-3
  type: t2.nano
  size: 20
  amis: #to be filled with system product

command:
  execute: "{{ .piper.cache }}/s3.eu-west-3.amazonaws.com/xbee.repository/providers/{{ .piper.os }}_{{ .piper.arch }}/aws"
